/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accepted-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accepted Actions */
        get: operations["accepted_actions_api_accepted_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/battery/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Battery Context */
        get: operations["battery_context_api_battery_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/battery/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Battery Simulation */
        get: operations["battery_simulation_api_battery_simulation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bid-stack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bid Stack */
        get: operations["bid_stack_api_bid_stack_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carbon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carbon */
        get: operations["carbon_api_carbon_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Stream update events; the client refetches the affected endpoints on each.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generation */
        get: operations["generation_api_generation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prices */
        get: operations["prices_api_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supply-demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supply Demand */
        get: operations["supply_demand_api_supply_demand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeseries */
        get: operations["timeseries_api_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptedAction
         * @description One accepted Balancing Mechanism action (BOALF); level_from → level_to is the ramp.
         */
        AcceptedAction: {
            /**
             * Acceptance Time
             * Format: date-time
             */
            acceptance_time: string;
            /** Bm Unit */
            bm_unit: string | null;
            /** Fuel Type */
            fuel_type: string | null;
            /** Level From */
            level_from: number;
            /** Level To */
            level_to: number;
            /** National Grid Bm Unit */
            national_grid_bm_unit: string;
            /** So Flag */
            so_flag: boolean;
            /** Unit Name */
            unit_name: string | null;
        };
        /**
         * BatteryContext
         * @description Supporting stats for the Battery Lab explainer tab.
         */
        BatteryContext: {
            /** Avg Export P Kwh */
            avg_export_p_kwh: number;
            /** Avg Import P Kwh */
            avg_import_p_kwh: number;
            /** Days */
            days: number;
            /** Demand Profile */
            demand_profile: components["schemas"]["DemandBucket"][];
            /** Export Tariff */
            export_tariff: string;
            /** Green Overlap Pct */
            green_overlap_pct: number | null;
            /** Import Tariff */
            import_tariff: string;
            /** Intraday */
            intraday: components["schemas"]["PriceCarbonBucket"][];
            /** Presets */
            presets: components["schemas"]["BatterySpec"][];
            /** Region */
            region: string;
            /** Tdcv Kwh */
            tdcv_kwh: number;
            /**
             * Window From
             * Format: date
             */
            window_from: string;
            /**
             * Window To
             * Format: date
             */
            window_to: string;
        };
        /**
         * BatterySimulation
         * @description All strategy runs for one battery preset, plus shared context.
         */
        BatterySimulation: {
            /** Baseline Cost Gbp Year */
            baseline_cost_gbp_year: number;
            battery: components["schemas"]["BatterySpec"];
            /** Days */
            days: number;
            /** Runs */
            runs: components["schemas"]["StrategyRun"][];
            /**
             * Window From
             * Format: date
             */
            window_from: string;
            /**
             * Window To
             * Format: date
             */
            window_to: string;
        };
        /**
         * BatterySpec
         * @description A battery preset with an indicative installed cost (0% VAT, 2026 market).
         */
        BatterySpec: {
            /** Capacity Kwh */
            capacity_kwh: number;
            /** Cost Gbp */
            cost_gbp: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Power Kw */
            power_kw: number;
            /** Round Trip Efficiency */
            round_trip_efficiency: number;
        };
        /**
         * BidStack
         * @description The balancing-mechanism offer stack for the latest settlement period, cheapest first.
         */
        BidStack: {
            /** Entries */
            entries: components["schemas"]["BidStackEntry"][];
            /** Settlement Period */
            settlement_period: number | null;
        };
        /** BidStackEntry */
        BidStackEntry: {
            /** Accepted */
            accepted: boolean;
            /** National Grid Bm Unit */
            national_grid_bm_unit: string;
            /** Offer Price */
            offer_price: number;
            /** Volume Mw */
            volume_mw: number;
        };
        /** Carbon */
        Carbon: {
            /**
             * From Ts
             * Format: date-time
             */
            from_ts: string;
            /** Intensity Gco2 */
            intensity_gco2: number | null;
            /** Intensity Index */
            intensity_index: string;
        };
        /** CarbonPoint */
        CarbonPoint: {
            /** Actual Gco2 */
            actual_gco2: number | null;
            /** Forecast Gco2 */
            forecast_gco2: number | null;
            /**
             * From Ts
             * Format: date-time
             */
            from_ts: string;
            /** Intensity Gco2 */
            intensity_gco2: number | null;
            /** Intensity Index */
            intensity_index: string;
        };
        /**
         * DemandBucket
         * @description Typical household demand in one settlement period (TDCV-scaled Elexon PC1).
         */
        DemandBucket: {
            /** Avg Kwh */
            avg_kwh: number;
            /** Settlement Period */
            settlement_period: number;
            /** Summer Weekday Kwh */
            summer_weekday_kwh: number;
            /** Winter Weekday Kwh */
            winter_weekday_kwh: number;
        };
        /**
         * DispatchBucket
         * @description The battery's average behaviour in one settlement period across the window.
         */
        DispatchBucket: {
            /** Charge Kwh */
            charge_kwh: number;
            /** Discharge Kwh */
            discharge_kwh: number;
            /** Export P Kwh */
            export_p_kwh: number;
            /** Import P Kwh */
            import_p_kwh: number;
            /** Intensity Gco2 */
            intensity_gco2: number | null;
            /** Settlement Period */
            settlement_period: number;
            /** Soc Kwh */
            soc_kwh: number;
        };
        /** GenerationMixItem */
        GenerationMixItem: {
            /** Fuel Type */
            fuel_type: string;
            /** Generation Mw */
            generation_mw: number;
            /** Share Pct */
            share_pct: number | null;
        };
        /** GenerationPoint */
        GenerationPoint: {
            /** Fuel Type */
            fuel_type: string;
            /** Generation Mw */
            generation_mw: number;
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /** Share Pct */
            share_pct: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntradayBucket
         * @description Distribution of a metric at a given hour-of-day across the profiled window.
         */
        IntradayBucket: {
            /** Hour */
            hour: number;
            /** P10 */
            p10: number;
            /** P25 */
            p25: number;
            /** P50 */
            p50: number;
            /** P75 */
            p75: number;
            /** P90 */
            p90: number;
        };
        /**
         * MetricProfile
         * @description How a metric typically behaves — across the day (bands) and the week (heatmap).
         */
        MetricProfile: {
            /** Days */
            days: number;
            /** Intraday */
            intraday: components["schemas"]["IntradayBucket"][];
            /** Metric */
            metric: string;
            /** Weekly */
            weekly: components["schemas"]["WeekdayHourCell"][];
        };
        /** MonthlySaving */
        MonthlySaving: {
            /** Carbon Saved Kg */
            carbon_saved_kg: number;
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Saving Gbp */
            saving_gbp: number;
        };
        /** Price */
        Price: {
            /** Apx Price */
            apx_price: number | null;
            /** N2Ex Price */
            n2ex_price: number | null;
            /** Net Imbalance Volume */
            net_imbalance_volume: number;
            /** Settlement Period */
            settlement_period: number;
            /** System Price */
            system_price: number;
        };
        /**
         * PriceCarbonBucket
         * @description Import-price distribution + typical export/carbon for one settlement period.
         */
        PriceCarbonBucket: {
            /** Carbon P50 */
            carbon_p50: number | null;
            /** Export P50 */
            export_p50: number;
            /** Import P10 */
            import_p10: number;
            /** Import P25 */
            import_p25: number;
            /** Import P50 */
            import_p50: number;
            /** Import P75 */
            import_p75: number;
            /** Import P90 */
            import_p90: number;
            /** Settlement Period */
            settlement_period: number;
        };
        /** PricePoint */
        PricePoint: {
            /** Apx Price */
            apx_price: number | null;
            /** N2Ex Price */
            n2ex_price: number | null;
            /** Net Imbalance Volume */
            net_imbalance_volume: number;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Settlement Period */
            settlement_period: number;
            /** System Price */
            system_price: number;
        };
        /**
         * Snapshot
         * @description Latest values across all domains for the dashboard's first paint.
         */
        Snapshot: {
            carbon: components["schemas"]["Carbon"] | null;
            /** Frequency Hz */
            frequency_hz: number | null;
            /** Generation */
            generation: components["schemas"]["GenerationMixItem"][];
            /** Measured At */
            measured_at: string | null;
            price: components["schemas"]["Price"] | null;
            supply_demand: components["schemas"]["SupplyDemand"] | null;
        };
        /**
         * StrategyRun
         * @description One simulated (strategy × optimizer) run over the window.
         */
        StrategyRun: {
            /** Carbon Saved Kg Year */
            carbon_saved_kg_year: number;
            /** Cycles */
            cycles: number;
            /** Monthly */
            monthly: components["schemas"]["MonthlySaving"][];
            /** Optimizer */
            optimizer: string;
            /** Payback Years */
            payback_years: number | null;
            /** Saving Gbp */
            saving_gbp: number;
            /** Saving Gbp Year */
            saving_gbp_year: number;
            /** Strategy */
            strategy: string;
            /** Typical Day */
            typical_day: components["schemas"]["DispatchBucket"][];
        };
        /** SupplyDemand */
        SupplyDemand: {
            /** Demand Mw */
            demand_mw: number;
            /** Settlement Period */
            settlement_period: number;
            /** Total Generation Mw */
            total_generation_mw: number | null;
            /** Transmission Demand Mw */
            transmission_demand_mw: number;
        };
        /** SupplyDemandPoint */
        SupplyDemandPoint: {
            /** Demand Mw */
            demand_mw: number;
            /**
             * Period Start
             * Format: date-time
             */
            period_start: string;
            /** Settlement Period */
            settlement_period: number;
            /** Total Generation Mw */
            total_generation_mw: number | null;
            /** Transmission Demand Mw */
            transmission_demand_mw: number;
        };
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Value */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeekdayHourCell */
        WeekdayHourCell: {
            /** Hour */
            hour: number;
            /** Median */
            median: number;
            /** Weekday */
            weekday: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accepted_actions_api_accepted_actions_get: {
        parameters: {
            query?: {
                /** @description Number of recent actions. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedAction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    battery_context_api_battery_context_get: {
        parameters: {
            query?: {
                /** @description Months of history to simulate. */
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatteryContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    battery_simulation_api_battery_simulation_get: {
        parameters: {
            query?: {
                battery?: "5kwh" | "10kwh" | "13.5kwh";
                /** @description Months of history to simulate. */
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatterySimulation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bid_stack_api_bid_stack_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidStack"];
                };
            };
        };
    };
    carbon_api_carbon_get: {
        parameters: {
            query?: {
                /** @description History window in hours. */
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarbonPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generation_api_generation_get: {
        parameters: {
            query?: {
                /** @description History window in hours. */
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    prices_api_prices_get: {
        parameters: {
            query?: {
                /** @description History window in hours. */
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_profile_get: {
        parameters: {
            query: {
                metric: "demand" | "generation" | "carbon" | "price";
                /** @description Days of history to profile. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    supply_demand_api_supply_demand_get: {
        parameters: {
            query?: {
                /** @description History window in hours. */
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyDemandPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeseries_api_timeseries_get: {
        parameters: {
            query: {
                metric: "demand" | "generation" | "carbon" | "price";
                granularity?: "sp" | "hour" | "day";
                /** @description Window in hours (max 30 days). */
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
